name: Merge Files

env:
  ACTION_MAIL: "o.gruetzmann@gmail.com"
  ACTION_NAME: "ogruetzmann"
  FILENAME_AIRSPACE: "TopSkyAirspace"
  FILENAME_AREAS: "TopSkyAreas"
  FILENAME_CALLSIGNS: "TopSkyCallsigns"
  FILENAME_CPDLC: "TopSkyCPDLC"
  FILENAME_MAPS: "TopSkyMaps"
  FILENAME_MSAW: "TopSkyMSAW"
  FILENAME_SETTINGS: "TopSkySettings"
  FILENAME_SSR: "TopSkySSRcodes"
  FILENAME_STCA: "TopSkySTCA"
  FILENAME_SYMBOLS: "TopSkySymbols"
  FILENAME_VIEWS: "TopSkyViews"

on:
  push:
    paths: 
      - '**/TopSky*/*'

jobs:
    Merge:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v2
          - name: Set Branch
            run: echo "ACTION_BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV
          - name: Merge TopSkyAirspace
            run: cat $GITHUB_WORKSPACE/$FILENAME_AIRSPACE/*.txt >> $FILENAME_AIRSPACE.txt
          - name: Merge TopSkyAreas
            run: cat $GITHUB_WORKSPACE/$FILENAME_AREAS/*.txt >> $FILENAME_AREAS.txt
          - name: Merge TopSkyCallsigns
            run: cat $GITHUB_WORKSPACE/$FILENAME_CALLSIGNS/*.txt >> $FILENAME_CALLSIGNS.txt
          - name: Merge TopSkyCPDLC
            run: cat $GITHUB_WORKSPACE/$FILENAME_CPDLC/*.txt >> $FILENAME_CPDLC.txt
          - name: Merge TopSkyMaps
            run: cat $GITHUB_WORKSPACE/$FILENAME_MAPS/*.txt >> $FILENAME_MAPS.txt
          - name: Merge TopSkyMSAW
            run: cat $GITHUB_WORKSPACE/$FILENAME_MSAW/*.txt >> $FILENAME_MSAW.txt
          - name: Merge TopSkySettings
            run: cat $GITHUB_WORKSPACE/$FILENAME_SETTINGS/*.txt >> $FILENAME_SETTINGS.txt
          - name: Merge TopSkySSRcodes
            run: cat $GITHUB_WORKSPACE/$FILENAME_SSR/*.txt >> $FILENAME_SSR.txt
          - name: Merge TopSkySTCA
            run: cat $GITHUB_WORKSPACE/$FILENAME_STCA/*.txt >> $FILENAME_STCA.txt
          - name: Merge TopSkySymbols
            run: cat $GITHUB_WORKSPACE/$FILENAME_SYMBOLS/*.txt >> $FILENAME_SYMBOLS.txt
          - name: Merge TopSkyViews
            run: cat $GITHUB_WORKSPACE/$FILENAME_VIEWS/*.txt >> $FILENAME_VIEWS.txt
          - name: Remove Old Files
            run: rm -rf ./Release/ > /dev/null
          - name: Move Files
            run: mkdir Release && mv *.txt ./Release/
          - name: Push
            uses: ludeeus/action-push@0.0.1
